### ISSUE TITLE
Error when trying to run script

### ISSUE THREAD

**Issue by ccastillo-id** [Nuix/Search-Module#4]
Hello, when I am trying to open this script in NUIX I get the following error

Unexpected Error
 
Message:
(NameError) uninitialized constant Nx
Stack Trace:
org.jruby.embed.EvalFailedException: (NameError) uninitialized constant Nx
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.nuix.script.e.a(SourceFile:62)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.nuix.script.e.a(SourceFile:59)
	at com.sun.proxy.$Proxy57.eval(Unknown Source)
	at com.nuix.script.a.a(SourceFile:289)
	at com.nuix.investigator.script.m.e(SourceFile:326)
	at com.nuix.investigator.script.m.c(SourceFile:277)
	at com.nuix.investigator.script.m.doInBackground(SourceFile:180)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jruby.exceptions.NameError: (NameError) uninitialized constant Nx	at org.jruby.RubyModule.const_missing(org/jruby/RubyModule.java:3744)
	at RUBY.<main>(C:\Users\srvNuix\AppData\Roaming\Nuix\Scripts\SearchModule_v3.15.0\SearchModule.nuixscript\SearchModule.rb:32)

It says it's trying to find the Nx.jar ? We are running this on a 8.6.2.414 instance. We tried to place the Nx.jar file in the same folder of this script and that still isn't working.

**Comment by ccastillo-id** [comment]
This is also occurred after attempting to run the intersection report script. That attempt failed and so along this search module.

**Comment by JuicyDragon** [comment]
Hello @ccastillo-id I believe what has happened is you downloaded those scripts using the Green download button
![image](https://user-images.githubusercontent.com/11775738/93920158-a24d0400-fcc3-11ea-8dfa-36784e3e606e.png)
rather than from the releases section
![image](https://user-images.githubusercontent.com/11775738/93920205-b3961080-fcc3-11ea-9adf-03fdc80b1444.png)
The green download button downloads a copy of the repository itself (basically just the source code).  The compiled JAR files are not kept in source control, just their source code.  The release Zip files contain the compiled dependencies.

In the case of Search Module I believe the error is misleading as to what the issue is.  Search module is an older script and has it's own JAR file named **SearchModule3GUI.jar** so dropping **Nx.jar** in the directory with the script wouldn't really help with that error.  The error mentions **Nx** because before I created the **Nx.jar** I was using the **Nx** name in other ways (a Ruby module in the case of Search Module).

Please download each of the scripts from their respective releases section.  Those release Zips should contain everything needed to run each script so I suspect that will resolve your issues.  If you still have issues after downloading the release Zips, please let me know and we can troubleshoot further.

**Comment by ccastillo-id** [comment]
We just upgraded to Nuix 8.8 and the Search Module opened with no issue. We can close this. Thanks!

**Comment by JuicyDragon** [comment]
Glad to hear it worked out!
