### ISSUE TITLE
Unable to run script \ Nx.jar file?

### ISSUE THREAD

**Issue by ccastillo-id** [Nuix/Search-Module#5]
**Issue**
Unable to run script. 

**ERROR**
Unexpected Error
 
Message:
(NameError) uninitialized constant Nx
Stack Trace:
org.jruby.embed.EvalFailedException: (NameError) uninitialized constant Nx
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.nuix.script.e.a(SourceFile:62)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.nuix.script.e.a(SourceFile:59)
	at com.sun.proxy.$Proxy58.eval(Unknown Source)
	at com.nuix.script.a.a(SourceFile:289)
	at com.nuix.investigator.script.m.e(SourceFile:326)
	at com.nuix.investigator.script.m.c(SourceFile:277)
	at com.nuix.investigator.script.m.doInBackground(SourceFile:180)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jruby.exceptions.NameError: (NameError) uninitialized constant Nx	at org.jruby.RubyModule.const_missing(org/jruby/RubyModule.java:3762)
	at RUBY.<main>(C:\ProgramData\Nuix\Scripts\SearchModule_v3.16.0\SearchModule.nuixscript\SearchModule.rb:32)
-------------------------------------------------------------------------------------------------------------------------------------------

Copeid the Nx.jar file from Nuix repo and placed it in C:\Program Files\Nuix\Nuix 8.8\lib

**ERROR:**

Unexpected Error
 
Message:
(NameError) uninitialized constant Nx
Stack Trace:
org.jruby.embed.EvalFailedException: (NameError) uninitialized constant Nx
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.nuix.script.e.a(SourceFile:62)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.nuix.script.e.a(SourceFile:59)
	at com.sun.proxy.$Proxy58.eval(Unknown Source)
	at com.nuix.script.a.a(SourceFile:289)
	at com.nuix.investigator.script.m.e(SourceFile:326)
	at com.nuix.investigator.script.m.c(SourceFile:277)
	at com.nuix.investigator.script.m.doInBackground(SourceFile:180)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jruby.exceptions.NameError: (NameError) uninitialized constant Nx	at org.jruby.RubyModule.const_missing(org/jruby/RubyModule.java:3762)
	at RUBY.<main>(C:\ProgramData\Nuix\Scripts\SearchModule_v3.16.0\SearchModule.nuixscript\SearchModule.rb:32)

**Comment by JuicyDragon** [comment]
Hello @ccastillo-id I see you figured out that is an error regarding a missing Nx.jar

For future reference, if you download a release ZIP from the releases section (see screenshot below), the requisite JAR files should all be present.  I suspect you downloaded using the the green "Code" button, which basically is downloading a copy of the repository itself, which we tend not to commit compiled binaries into.

![image](https://user-images.githubusercontent.com/11775738/103807552-638d5080-500b-11eb-9018-9e92e8df974c.png)
